[package]
name = "dashboard"
version = "0.1.0"
authors = ["Алексей Карасев <karasev.alexey@gmail.com>"]

[lib]
name = "dashboard_core"

[dependencies]
config = "0.9"
serde = "1.0"
serde_derive = "1.0"
